### ISSUE TITLE
Implementing Putty-Clay and PDE into new formalism

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#108]
Motivations:
--------------
* Since PR #104 and #105 , the new formalism and all its major functionalities are in place.
* In the meantime, @MattArran proposed PR #88 to implement a new model that includes PDE support, but this was proposed based on the previous formalism
* Furthermore, since we implemented the possibility of running multiple systems the low-level has changed a bit and there may be subtleties in the implementation of pde support in the new formalism

Proposition:
--------------
* I will propose a PR to replace PR #88, with the new formalism
* It will be largely inspired from PR #88, but adapted to the new code structure
* Both @Dalus and @MattArran should review it to double-check for conformity with their needs

**Comment by Didou09** [comment]
I already have a few questions:
---------------------------------
* units
   - `y` or `yr` ?
   - `Dollars` vs `dollars` vs `$`    
   On this I think we should avoid the symbol `$` to avoid confusion with the latex-formatting flag which we want to use too
* Quantities:
    - `W` (money) vs `w` (money/human/year) ? Can they both be useful or shall we keep only one ? If we keep only one I guess it is `w` right ? Shall I replace W by w in `_model_GK.py` ?

**Comment by DaluS** [comment]
> * `y` or `yr` ?
> * `Dollars` vs `dollars` vs `$`
>   On this I think we should avoid the symbol `$` to avoid confusion with the latex-formatting flag which we want to use too

`yr`, `dollars` seems the right choice. I agree with `$` being dangerous. 

>   * `W` (money) vs `w` (money/human/year) ? Can they both be useful or shall we keep only one ? If we keep only one I guess it is `w` right ? Shall I replace W by w in `_model_GK.py` ?

Yes the typo was on my side, `W=wL` and both should be defined !

**Comment by MattArran** [comment]
On units: yep, `yr` and `dollars` seem best given the issues with `$`
On quantities:  if aggregate wages `W` are to be defined, their units should be money/year
On the model:
- `np.nonzero` returns a tuple of arrays, so for 1-D array `x`, `np.nonzero(x)[0]` is the array of interest.
- We take the first index `np.nonzero(productivity_fn >= w)[0][0]` because we want a single value, equal to the first index `i` at which it is profitable to run a machine with capital-labor ratio `kl_ratio[i]`
- `kl_ratio` and `productivity_fn` are monotonically increasing, so `kl_ratio[i]` corresponds to the minimum capital-labor ratio
- There will normally be many capital-labor ratios at which it would be profitable to run a machine, but this is the `minimum_profitable_kl_ratio_index` function.
- Probably, we should add a try-except to ensure that there is at least one such index, but the continuous system that we're approximating can never evolve from a situation in which there is a minimal profitable capital-labor ratio $k_{min}$ to one in which there isn't (as $k_{min}$ increases to the maximal available $k$, $L$ will decrease towards 0, so that $w$ decreases towards 0).

On the PR proposal: sounds good! Happy to help the conversion process if I can.

**Comment by Didou09** [comment]
> kl_ratio and productivity_fn are monotonically increasing, so kl_ratio[i] corresponds to the minimum capital-labor ratio

OK, so taking only the first non-zero is ok to get the minimum because productivity_fn is monotonically increasing.

Thanks very much for your detailed and self-explanatory answer :-)

**Comment by DaluS** [comment]
I transmit it into #152 !
