### ISSUE TITLE
Nomenclature: parameters, variables, functions...

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#26]
This is just so we have an official place where the nomenclature is defined.

Do we agree on the following definitions:
* Parameters:
      - They are constant and used to parameterize the model
      - They are typically represented by a scalar (`int` of `float`) or a flag (`bool` or `str`)
      - They are _**exogenous**_
* Variable:
      - They are quantities that can vary in time and space (and possibly other dimensions)
      - They are computed by the model / solver in a consistent way (they are _**endogenous**_)
      - They are typically represented by `numpy arrays` 
* functions:
     - They can depend both on parameters and variables
     -  They are `callable` objects

I wanted to clarify because when @DaluS asked for a fusion between `_def_parameters.py` and `VariableDictionnary.py` I noticed these were 2 sets of different objects (parameters vs variables), so I wasn't sure whether you wanted parameters and variables to have the same fields (`name`, `type`...) of whether they should be treated separately, with different fields.

I figured that giving them similar fields would make sense and that you would have said it if you thought otherwise, so I did give parameters in `_def_parameters.py` some fiedls taken from `VariableDictionnary.py`. 
Can you confirm I interpreted correctly ?

This is also the place to discuss those details, so don't hesitate.

**Comment by DaluS** [comment]
> This is just so we have an official place where the nomenclature is defined.
> 
> Do we agree on the following definitions:
> 
> * Parameters:
>   - They are constant and used to parameterize the model
>   - They are typically represented by a scalar (`int` of `float`) or a flag (`bool` or `str`)
>   - They are _**exogenous**_

Yes. BUT it is possible to have array/list of them, with a size consistent with parNum(['Nx']). In that case, the actual architecture will run in parrallel all systems with for each a different parameter value (Very practical to see influence of initial conditions/ sensibility, or do system interactions through coupling matrices). An array of parameter can be a proxy of parameter evolution through space. I take advantage of python implicitely knowing that scalar*array is an array of the scalar everywhere*array.
They should not be varying in the model (and as such not stocked with variables), BUT it should be easy for the modeller to change from a parameter to a variable (for example, we use here constant interest for debt `r`, but a modeler could decide that now `r` is a function of your solvability)

> * Variable:
>   - They are quantities that can vary in time and space (and possibly other dimensions)
>   - They are computed by the model / solver in a consistent way (they are _**endogenous**_)
>   - They are typically represented by `numpy arrays`

Variables will always be numpy aray, are endogeneous. 
* Some can be defined as "State variable" ( for example the output `Y` is defined by the capital `K` and the return of capital on input `nu` ), which are in that case defined through `self.intermediaryfuncs` . 
* Some can be defined as "differential variable", I.E. it's not the value which is defined but its derivate ( Capital `K` is defined by its evolution, like `dK/dt = I - K*delta_k`. Some state variables  are needed to define the evolution of "differential variable". 
*  `self.intermediaryfuncs` contains both needed state variable to define the differential variables and some useful intermediary state variables "auxilliary variables" for the user to understand what is happening. For example, `g=dot{Y}/Y' is a state variable in goodwin-keen but its calculation is not needed to capture the dynamics. 


> * functions:
>   
>   * They can depend both on parameters and variables
>   * They are `callable` objects

* Those functions are what I call intermediary variables, and indeed are depending of parameters and variables :) 

> I wanted to clarify because when @DaluS asked for a fusion between `_def_parameters.py` and `VariableDictionnary.py` I noticed these were 2 sets of different objects (parameters vs variables), so I wasn't sure whether you wanted parameters and variables to have the same fields (`name`, `type`...) of whether they should be treated separately, with different fields.
> I figured that giving them similar fields would make sense and that you would have said it if you thought otherwise, so I did give parameters in `_def_parameters.py` some fiedls taken from `VariableDictionnary.py`.
> Can you confirm I interpreted correctly ?

* Yes ! I think it's practical to have them at the same place (at least in term of default value in a megadictionnary). We will need a practical interface for the user when he wants to modify these values (because looking at this very long list of variable/parameters to find one value and test it is quite heavy and slow). I did it in the existing code with `Par.Modifications (params, parNum)` which allow the user to define some new values. 

> This is also the place to discuss those details, so don't hesitate.

Good idea ! Here is what I think about : 

* All the "Typical values" should be stocked somewhere far from the typical user (_def_parameters looks great), however he should 
     * a) check all values indeed taken in his model ( self.parameters for parameters, self.variables for differentially defined variables, the one we will solve) 
     * b) be able to modify them (create an array with different values for example)
* Intermediaryfuncs can be separated into two dictionnary : 
     * a) The one needed ( the true intermediary)
     * b) The auxilliary values (solved on the side)
* The order of functions in intermediaryfuncs should be enough to run f (maybe we need an 'order' list of variable since dictionnary's order is not always well defined if I remember well). The order for self.variable should not be useful as it doesn't rely on itself. Of course this order is important otherwise the system will call undefined variables and crash
* in `f`, y dictionnary is reallocated at each timestep, variable per variable through dictionnary comprehension. This is I guess one bottleneck, there are two possibilities : 
    * a) Initialisation of the dictionnary with `np.zeros(parNum['Nx'])` at each f iteration (no reallocation during one loop)
    * b) Pre-initialisation of the dictionnary y ( so that it is self.y ) with the relevant variables. This is the fastest numerically, but we should be very cautious the system indeed updates all variables and don't take the value from the iteration before
    * self. description should give 'help(self)' or something like

I create a new issue with a pull request with a part of the implementation

**Comment by DaluS** [comment]
I think I did some bad classification, there is a third category which should exist : 

* **extensive** as Kapital for exemple
* **intensive** as growth rate
* **dimensionless** as lambda (or a reynolds number)

I havn't thought about that before, I should update the system on this

**Comment by Didou09** [comment]
OK

**Comment by DaluS** [comment]
This is now discussed in #47 with the new structure in mind
