### ISSUE TITLE
Output data saving

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#3]
Motivation:
--------------
* It seems that the code currently allows to save the modules themselves (function Miscfunc.savedata())
* In particular, it saves Main.py and FunctionsGoodwin.py, presumably to save the input parameters stored in these.
* As far as I understand it, the output data does not seem to be saved 
* In principle, storing a copy of the code is already done by git and github

Proposition:
-----------------
* In terms of general strategy, and architecture, for traceability, reproducibility and ease of use, I would recommend to:
   - Make sure all input parameters can be put into a single input dict
   - Make sure the solver / main function can take that input dict 
   - Make sure all produced results can be put into a single output dict
   - implement the possibility of saving that output dict, into a npz file
   - Implement an explicit naming convention for saved files: typically:
         `Input_ParmeterName1ParameterValue1_ParameterName2ParameterValue2_..._ParameterNameNParameterValueN.npz`
        `Output_ParmeterName1ParameterValue1_ParameterName2ParameterValue2_..._ParameterNameNParameterValueN.npz`
      Where only the most relevant parameters are included (file names are often limited in length)

**Comment by DaluS** [comment]
Yes this saving method is weird and in fact I never used it. I think I'll add a method in the class to : 
* Stock all the necessary data generated by a run
* Save the class object with the new values
* Expand back the data when needed

About parameters and input, for me there are three different type of values (hence 3 dictionnary for the moment) : 
* the "physical/behavioral" parameters (price markup, efficiency of capital...)
* the numerical parameters ( Number of system solved in parrallel, time increment...)
* the initial conditions of the system
I like the three of them to be different, but we can regroup them into one if you think that's more suitable. Or having a dictionnary of dictionnary which regroup all of them ? 

For saved files I think it'd be complex to find the right naming convention. We can ask the user to name the run and put this as the name, with a default name otherwise (typically the date) and a .txt of the parameters on the side (that can be easily read)

**Comment by DaluS** [comment]
As mentionned in #48 , we should decide on : 
* The type of data we want to save
* Its format
* The structure of saving folders 

Before coding it !

**Comment by DaluS** [comment]
Done
