### ISSUE TITLE
Parameters : clairifications and strategy

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#8]
This is probably mostly for @DaluS 

Clarifications needed regarding parameters:
-----------------------------------------------------------

In the current `Parameters.BasicParameters()` function I find the following possible conflicts that may require clarification:

1) Two variable with the same comment: are they redundant ? Is it the same variable?
```
    'dPBS'   : - 0.005,               # Growth rate of back-stop technology price   
    'dPc'    : 0, #[CORRECT]          # Growth rate of back-stop technology price 
```

2) In a previous version there was a variable called `pK` (# Price consumption of capital), I don't see it anymore, has it been replaced ?

3) Same question for variables `phiType` and `phislope`?

4) Same question for `time_safety`

Other question:
---------------------
* Shall we produce a single dictionary with all parameters of a dict of sub-dict of parameters, grouped by theme ?
* Another way to ask that question could be: how similar (or different) will models from various articles be ? Will they have a lot of variables in common or are they very different ?

Maybe answering this second questions first requires dealing with issue  #7 ?

**Comment by DaluS** [comment]
* I removed these variables because there were depreciated ( phitype and phislope, now the philips curve is inside the model, time_safety is because some typical time were not effectively defined and dPc was not finished)
* I think we shall produce one dictionnary that's fine !  (see #10  i think for the subject ! ) 
* The convention for variable name is well established in the field, so if two authors use the same variable name it should be the same thing ( for a few greek letters one can add another letter to be sure, for example I used gammaP for gamma related to price). Using same name as a basis seems fine I guess

**Comment by Didou09** [comment]
> * I removed these variables because there were depreciated ( phitype and phislope, now the philips curve is inside the model, time_safety is because some typical time were not effectively defined and dPc was not finished)

ok

> * I think we shall produce one dictionnary that's fine !  (see [Issue006 choice of system of equations #10](https://github.com/DaluS/GEMMES/pull/10)  i think for the subject ! )

Yes, I've started doing it with a single large dict in #10 , but if you prefer sub-dictionnaries I can still change strategy, just asking for confirmation (and we can always change later if we realize the alternative is better).

> * The convention for variable name is well established in the field, so if two authors use the same variable name it should be the same thing ( for a few greek letters one can add another letter to be sure, for example I used gammaP for gamma related to price). Using same name as a basis seems fine I guess

ok good to know, wasn't sure about that, thanks
