### ISSUE TITLE
Small syntax changes for compacity / more control

### ISSUE THREAD

**Issue by Didou09** [DaluS/GEMMES#83]
Motivations:
----------------
* PR #72, #73, #74 introduced sevral new methods / routines
* I noticed that some parts of the code can be written either in a more compact way, or in way that matches better the best practices and give more control on the result

Proposition:
----------------
* A PR will b proposed that will suggest some minor changes on these points
* It won't changes the functionality and will be an optional PR, just for clean-up, you can decide to ignore it

**Comment by DaluS** [comment]
Yes ! Please be sure to check the content I sent you ( the presentations/ Ipython notebook ) for a better view of what's been done. 

Make sure that when it can be more compact, it is also easy to understand. A nested nested nested function is indeed very compact, but it's really difficult to understand (and modify it if necessary). So please be sure that the code is still easy to understand (for example it was not the case of set_dparam, after multiple attempts I had to recode huge chuncks because I was not able to understand the philosophy nor the way it functioned)

**Comment by DaluS** [comment]
Core written in a more practical way in previous PR
