### ISSUE TITLE
For later : A logic graph for variables 

### ISSUE THREAD

**Issue by DaluS** [DaluS/GEMMES#92]
The idea is to generate for each model spontaneously a graph on how variables are linked to each others, to see the network of relations. Something like this : 
![image](https://user-images.githubusercontent.com/11523050/129971169-1db49bf4-eb68-4f23-ba52-41bc5306224a.png)
 But cleaner :)

**Comment by Didou09** [comment]
Comment: I agree this is a good idea and would b useful for users, but I cannot volunteer to do it because due to limited time I prefer to focus on low-level tasks.

Here are a few libraries that can help you:
* http://furius.ca/snakefood/#documentation 
* https://pycallgraph.readthedocs.io/en/master/index.html
* https://graph-tool.skewed.de/
* https://networkx.org/
* https://igraph.org/redirect.html

I do not have experience with any of them, just did a quick search

In terms of code, you'll find all necessary info (kwdargs for each function) in the 2 following dict
Taking for example function 'kappa' of model GK:

```
In [1]: import _core

In [2]: hub = _core.Hub('GK')                                                                                                                                                         

In [3]: hub.dparam['kappa']['kargs']                     # list of all keyword args                                                                                                                               
Out[3]: ['k0', 'k1', 'k2', 'Pi', 'Y']

In [4]: hub.dparam['kappa']['args']                        # dict of keyword args classified by eqtype (None = fixed-value parameter)                                                                                                                   
Out[4]: {None: ['k0', 'k1', 'k2'], 'param': [], 'ode': [], 'statevar': ['Pi', 'Y']}
```

**Comment by DaluS** [comment]
Awesome. Thanks for all the libraries, I'm going to explore that. The args from dparam is a huge help also clearly, you did almost all the work for me :)

**Comment by DaluS** [comment]
Here is a first step for a GK Model, I can't install graphviz on my PC so the layout is not great, however that's a start 
![image](https://user-images.githubusercontent.com/11523050/142693914-d4e0edf5-9be8-4cb0-a308-eeb2aaaecf45.png)
